In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
num_inputs=2
num_neurons=3

In [3]:
x0=tf.placeholder(tf.float32,[None,num_inputs])
x1=tf.placeholder(tf.float32,[None,num_inputs])

In [4]:
Wx=tf.Variable(tf.random_normal(shape=[num_inputs,num_neurons]))
Wy=tf.Variable(tf.random_normal(shape=[num_neurons,num_neurons]))

In [5]:
b=tf.Variable(tf.zeros([1,num_neurons]))

In [6]:
y0=tf.tanh(tf.matmul(x0,Wx)+b)
y1=tf.tanh(tf.matmul(y0,Wy)+tf.matmul(x1,Wx)+b)

In [7]:
init=tf.global_variables_initializer()

In [8]:
x0_batch=np.array([[0,1],[2,3],[4,5]])
x1_batch=np.array([[100,101],[102,103],[104,105]])

In [9]:
np.array([[0,1],[2,3],[4,5]])

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
with tf.Session() as sess:
    sess.run(init)
    y0_out_val,y1_out_val=sess.run([y0,y1],feed_dict={x0:x0_batch,x1:x1_batch})

In [12]:
y1_out_val

array([[-1.        , -1.        ,  0.99999368],
       [-1.        , -1.        ,  0.99999559],
       [-1.        , -1.        ,  0.99999613]], dtype=float32)

In [13]:
y0_out_val

array([[-0.36392349, -0.96713448,  0.74024278],
       [-0.99824965, -0.9990828 ,  0.76921594],
       [-0.99999654, -0.99997485,  0.7953375 ]], dtype=float32)